version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - backend-network

  emailservice: 
    image: email_services:1.0
    environment:
      HOST_EMAIL: sandbox.smtp.mailtrap.io
      HOST_PORT: 2525
      AUTH_EMAIL: 0851f49bc8ed23
      AUTH_EMAIL_PASSWORD: 46f98cc9b1b43b
      PORT: 3001
      HOST: '0.0.0.0'    
    ports:
      - "3001:3001"
    networks:
      - backend-network

  redis-db:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
networks:
  backend-network:
  
volumes:
  cache:
